---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobdemo
  labels:
    purpose: cronjob 
spec:
  schedule: '*/5 * * * *' 
  jobTemplate:
    metadata: 
      labels: 
        purpose: jobdemo
    spec:
      restartPolicy: OnFailure 
      backoffLimit: 3
      template: 
        metaddata: 
          labels: 
            app: batch
        spec: 
          containers: 
            - name: batchdemo
              image: alpine
              command: 
                - sleep 
                - 10s   
        