---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: httpd-rs
  labels: 
    purpose: demohttpd
spec: 
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels:
      app: httpd-1
      release: v1.1
  template: 
    metadata: 
      labels:
        app: httpd-1
        release: v1.1
    spec: 
      containers: 
        - name: mycont
          image: httpd:2.4
          command:
            - sleep
            - 1d
          ports:
            - containerPort: 8080
              protocol: TCP  